title: CSE 8A/6R Fall 2025
description: The official website for CSE 8A/6R at UC San Diego (Fall 2025).
remote_theme: just-the-docs/just-the-docs
color_scheme: light

domain: cse8a-6r-fall2025.github.io
url: https://cse8a-6r-fall2025.github.io

logo: "/assets/new_logo.png"
favicon_ico: "/assets/favicon/favicon.ico"

math: katex

aux_links:
  Gradescope: "https://www.gradescope.com/"
  Textbook: "https://cogniterra.org/course/705/"
  EdStem: "https://edstem.org/us/courses/87720/discussion"
  Canvas: "https://canvas.ucsd.edu/courses/68535"
aux_links_new_tab: true

footer_content: 'University of California San Diego. Built with <a href="https://github.com/just-the-docs/just-the-docs">Just the Docs</a>.'
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

callouts:
  note:
    color: blue
    title: note
  warning:
    color: red
    title: warning
  important:
    color: green
    title: important
  checkoff:
    color: green
    title: 📋 Check your progress!
  owntime:
    color: grey-dk
    title: 🚀 In your own time
  exercise:
    color: purple
    title: 💪 Exercise
  midterm:
    color: red
    title: Midterm Exam

plugins:
  - jekyll-remote-theme

mermaid:
  version: 11.6.0

# Enable table of contents
toc:
  enabled: true
  h_min: 2
  h_max: 3
